<?php
require __DIR__ . '/../layouts/header.php';Auth::requireRole('admin');
require_once __DIR__ . '/../../core/Csrf.php';require_once __DIR__ . '/../../core/Pagination.php';
$pagination=Pagination::paginateArray($incentives,'incentives_page','incentives_per_page',[10,20,50,100]);$rows=$pagination['rows'];
?>
<div class="app-shell d-flex"><?php require __DIR__ . '/../layouts/sidebar_admin.php';?><div class="content p-4">
  <div class="page-toolbar mb-3"><div><h3 class="mb-0">Incentivos y bonos</h3><div class="text-muted small">Gestiona montos, reglas, estado y publicación para los trabajadores.</div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createIncentive">+ Nuevo incentivo</button></div>
  <?php if(!empty($msg)):?><div class="alert alert-<?=Helpers::e($msg['type'])?>"><?=Helpers::e($msg['text'])?></div><?php endif;?>
  <div class="card shadow-sm mb-3"><div class="card-body"><form method="GET" class="row g-2 align-items-end">
    <div class="col-md-5"><label class="form-label">Buscar</label><input class="form-control" name="q" value="<?=Helpers::e($search)?>" placeholder="Título o descripción"></div>
    <div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="status"><option value="">Todos</option><option value="active" <?=$status==='active'?'selected':''?>>Activo</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>Inactivo</option></select></div>
    <div class="col-md-2"><label class="form-label">Publicación</label><select class="form-select" name="publication"><option value="">Todas</option><option value="published" <?=$publication==='published'?'selected':''?>>Publicado</option><option value="hidden" <?=$publication==='hidden'?'selected':''?>>Oculto</option></select></div>
    <div class="col-md-3 d-flex gap-2"><button class="btn btn-outline-primary flex-grow-1">Filtrar</button><a class="btn btn-outline-secondary" href="<?=Helpers::e(BASE_URL.'/admin/incentives')?>">Limpiar</a></div>
  </form></div></div>
  <div class="card shadow-sm"><div class="card-body table-responsive"><table class="table align-middle"><thead><tr><th>Título</th><th class="text-end">Monto</th><th>Reglas o descripción</th><th>Estado</th><th>Publicación</th><th>Actualizado</th><th>Acciones</th></tr></thead><tbody>
  <?php foreach($rows as $item):?><tr><td class="fw-semibold"><?=Helpers::e($item['title'])?></td><td class="text-end">S/ <?=number_format((float)$item['amount'],2)?></td><td style="max-width:380px"><div class="text-truncate"><?=Helpers::e($item['description']?:'Sin descripción')?></div></td><td><span class="badge text-bg-<?=(int)$item['is_active']===1?'success':'secondary'?>"><?=(int)$item['is_active']===1?'Activo':'Inactivo'?></span></td><td><span class="badge text-bg-<?=(int)$item['is_published']===1?'primary':'dark'?>"><?=(int)$item['is_published']===1?'Publicado':'Oculto'?></span></td><td><?=Helpers::e(date('d/m/Y H:i',strtotime($item['updated_at'])))?></td><td class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editIncentive<?=(int)$item['id']?>">Editar</button><form method="POST" onsubmit="return confirm('¿Eliminar este incentivo o bono?');"><input type="hidden" name="_csrf" value="<?=Helpers::e(Csrf::token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><button class="btn btn-sm btn-outline-danger">Eliminar</button></form></td></tr>
    <div class="modal fade" id="editIncentive<?=(int)$item['id']?>" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><input type="hidden" name="_csrf" value="<?=Helpers::e(Csrf::token())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><div class="modal-header"><h5 class="modal-title">Editar incentivo o bono</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><?php $formItem=$item;require __DIR__.'/partials/incentive_fields.php';?></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar cambios</button></div></form></div></div></div>
  <?php endforeach;?><?php if(empty($rows)):?><tr><td colspan="7" class="text-muted text-center py-4">No hay incentivos o bonos registrados.</td></tr><?php endif;?></tbody></table><?=Pagination::render($pagination['meta'])?></div></div>
</div></div>
<div class="modal fade" id="createIncentive" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><input type="hidden" name="_csrf" value="<?=Helpers::e(Csrf::token())?>"><input type="hidden" name="action" value="create"><div class="modal-header"><h5 class="modal-title">Nuevo incentivo o bono</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><?php $formItem=['title'=>'','amount'=>'','description'=>'','is_active'=>1,'is_published'=>0];require __DIR__.'/partials/incentive_fields.php';?></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Crear incentivo</button></div></form></div></div></div>
<?php require __DIR__ . '/../layouts/footer.php';?>
