<?php
require __DIR__.'/../layouts/header.php'; Auth::requireRole('admin');
require_once __DIR__.'/../../core/Pagination.php';
$pagination=Pagination::paginateArray($functions,'functions_page','functions_per_page',[10,20,50]); $rows=$pagination['rows'];
?>
<div class="app-shell d-flex"><?php require __DIR__.'/../layouts/sidebar_admin.php';?><div class="content p-4">
  <div class="page-toolbar mb-3"><div><h3 class="mb-0">Funciones por rol y área</h3><div class="text-muted small">Define las responsabilidades de Salón, Barra, Cocina, Campo y demás áreas.</div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createJobFunction">+ Registrar funciones</button></div>
  <?php if($msg):?><div class="alert alert-<?=Helpers::e($msg['type'])?>"><?=Helpers::e($msg['text'])?></div><?php endif;?>
  <div class="card shadow-sm mb-3"><div class="card-body"><form method="GET" class="row g-2 align-items-end">
    <div class="col-md-4"><label class="form-label">Buscar</label><input class="form-control" name="q" value="<?=Helpers::e($search)?>" placeholder="Título o función"></div>
    <div class="col-md-3"><label class="form-label">Área</label><select class="form-select" name="area_id"><option value="0">Todas</option><?php foreach($areas as $area):?><option value="<?=(int)$area['id']?>" <?=$areaId===(int)$area['id']?'selected':''?>><?=Helpers::e($area['name'])?></option><?php endforeach;?></select></div>
    <div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="status"><option value="">Todos</option><option value="active" <?=$status==='active'?'selected':''?>>Activo</option><option value="inactive" <?=$status==='inactive'?'selected':''?>>Inactivo</option></select></div>
    <div class="col-md-2"><label class="form-label">Publicación</label><select class="form-select" name="publication"><option value="">Todas</option><option value="published" <?=$publication==='published'?'selected':''?>>Publicado</option><option value="hidden" <?=$publication==='hidden'?'selected':''?>>Oculto</option></select></div>
    <div class="col-md-1"><button class="btn btn-outline-primary w-100">Buscar</button></div>
  </form></div></div>
  <div class="card shadow-sm"><div class="card-body table-responsive"><table class="table align-middle"><thead><tr><th>Título</th><th>Área</th><th>Funciones</th><th>Estado</th><th>Publicación</th><th>Acciones</th></tr></thead><tbody>
  <?php foreach($rows as $item):?><tr><td class="fw-semibold"><?=Helpers::e($item['title'])?></td><td><span class="badge text-bg-info"><?=Helpers::e($item['area_name'])?></span></td><td style="max-width:360px"><div class="text-truncate"><?=Helpers::e($item['description'])?></div></td><td><span class="badge text-bg-<?=(int)$item['is_active']===1?'success':'secondary'?>"><?=(int)$item['is_active']===1?'Activo':'Inactivo'?></span></td><td><span class="badge text-bg-<?=(int)$item['is_published']===1?'primary':'dark'?>"><?=(int)$item['is_published']===1?'Publicado':'Oculto'?></span></td><td><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-info" data-bs-toggle="modal" data-bs-target="#viewFunction<?=(int)$item['id']?>">Ver</button><button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#editFunction<?=(int)$item['id']?>">Editar</button><form method="POST" onsubmit="return confirm('¿Eliminar este registro?');"><input type="hidden" name="_csrf" value="<?=Helpers::e(Csrf::token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><button class="btn btn-sm btn-outline-danger">Eliminar</button></form></div></td></tr>
  <div class="modal fade" id="viewFunction<?=(int)$item['id']?>" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><?=Helpers::e($item['title'])?></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><strong>Área:</strong> <?=Helpers::e($item['area_name'])?></div><div class="border rounded p-3" style="white-space:pre-line"><?=Helpers::e($item['description'])?></div></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button></div></div></div></div>
  <div class="modal fade" id="editFunction<?=(int)$item['id']?>" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><input type="hidden" name="_csrf" value="<?=Helpers::e(Csrf::token())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=(int)$item['id']?>"><div class="modal-header"><h5 class="modal-title">Editar funciones</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?php $formItem=$item; require __DIR__.'/partials/job_function_fields.php';?></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar cambios</button></div></form></div></div></div>
  <?php endforeach;?><?php if(!$rows):?><tr><td colspan="6" class="text-center text-muted py-4">No hay funciones registradas.</td></tr><?php endif;?></tbody></table><?=Pagination::render($pagination['meta'])?></div></div>
</div></div>
<div class="modal fade" id="createJobFunction" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST"><input type="hidden" name="_csrf" value="<?=Helpers::e(Csrf::token())?>"><input type="hidden" name="action" value="create"><div class="modal-header"><h5 class="modal-title">Registrar funciones</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><?php $formItem=[]; require __DIR__.'/partials/job_function_fields.php';?></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Registrar</button></div></form></div></div></div>
<?php require __DIR__.'/../layouts/footer.php';?>
